---
# source: EQ setting for Sennheiser HD650 (Harman AE/OE) by oratory1990 from
# 14.04.21:
# https://www.dropbox.com/s/zr5tqw0qojom9uh/Sennheiser%20HD650.pdf?dl=0
#
# BiQuadDesigner for Free Biquad filters (used instead of shelving fitlers):
# https://arachnoid.com/BiQuadDesigner/index.html

devices:
  samplerate: 192000
  chunksize: 4096
  target_level: 2048
  capture:
    type: Alsa
    channels: 2
    device: "hw:CARD=GenericStereoAu,DEV=1"
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:CARD=GenericStereoAu,DEV=0"
    format: S32LE

filters:
  hd650_oratory1990_gain:
    type: Gain
    parameters:
      gain: -9.3
      
  hd650_oratory1990_band01:
    type: Biquad
    parameters:
      type: Peaking
      freq: 20
      gain: 4.0
      q: 1.1
      
  hd650_oratory1990_band02:
    type: Biquad
    parameters:
      type: Peaking
      freq: 97
      gain: -2.4
      q: 0.7
            
  hd650_oratory1990_band03:
    type: Biquad
    parameters:
      type: Free
      a1: -1.99585206
      a2: 0.99586065
      b0: 1.00077277
      b1: -1.99584827
      b2: 0.99509167

  hd650_oratory1990_band04:
    type: Biquad
    parameters:
      type: Peaking
      freq: 215
      gain: -1.8
      q: 1.1  
      
  hd650_oratory1990_band05:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1300
      gain: -1.4
      q: 1.5
      
  hd650_oratory1990_band06:
    type: Biquad
    parameters:
      type: Free
      a1: -1.89917867
      a2: 0.90402281
      b0: 1.40128681
      b1: -2.68366036
      b2: 1.28721770
       
  hd650_oratory1990_band07:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2700
      gain: -1.3
      q: 3.0
      
  hd650_oratory1990_band08:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3250
      gain: -3.0
      q: 2.7
      
  hd650_oratory1990_band09:
    type: Biquad
    parameters:
      type: Peaking
      freq: 5400
      gain: -1.6
      q: 3.0
      
  hd650_oratory1990_band10:
    type: Biquad
    parameters:
      type: Free
      a1: -1.53832894
      a2: 0.62649119
      b0: 0.73930508
      b1: -1.07617941
      b2: 0.42503658

pipeline:
  - type: Filter
    channel: 0
    names:
      - hd650_oratory1990_gain
      - hd650_oratory1990_band01
      - hd650_oratory1990_band02
      - hd650_oratory1990_band03
      - hd650_oratory1990_band04
      - hd650_oratory1990_band05
      - hd650_oratory1990_band06
      - hd650_oratory1990_band07
      - hd650_oratory1990_band08
      - hd650_oratory1990_band09
      - hd650_oratory1990_band10
  - type: Filter
    channel: 1
    names:
      - hd650_oratory1990_gain
      - hd650_oratory1990_band01
      - hd650_oratory1990_band02
      - hd650_oratory1990_band03
      - hd650_oratory1990_band04
      - hd650_oratory1990_band05
      - hd650_oratory1990_band06
      - hd650_oratory1990_band07
      - hd650_oratory1990_band08
      - hd650_oratory1990_band09
      - hd650_oratory1990_band10
   

